{
 "title": "Sales Performance Dashboard",
 "time": { "from": "2023-01-23T00:00:00.000Z", "to": "2025-01-23T00:00:00.000Z" },
 "panels": [
  {
   "title": "Sales by Category",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    category,\n    SUM(quantity * price) AS total_sales\nFROM sales\nGROUP BY category;"
    }
   ]
  },
  {
   "title": "Sales Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    sale_date AS time,\n    SUM(quantity * price) AS total_sales\nFROM sales\nGROUP BY sale_date\nORDER BY sale_date;"
    }
   ]
  },
  {
   "title": "Top 10 Products ",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    product_name,\n    SUM(quantity * price) AS total_revenue\nFROM sales\nGROUP BY product_name\nORDER BY total_revenue DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Average Sale Price Over Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    sale_date AS time,\n    AVG(price) AS avg_price\nFROM sales\nGROUP BY sale_date\nORDER BY sale_date;"
    }
   ]
  },
  {
   "title": "Monthly Sales Trends",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('month', sale_date) AS time,\n    SUM(quantity * price) AS total_sales\nFROM sales\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sales Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n    sale_date AS time,\n    SUM(quantity * price) AS total_sales\nFROM sales\nGROUP BY sale_date\nORDER BY sale_date;"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(quantity * price) AS total_revenue FROM sales;"
    }
   ]
  }
 ]
}